server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ngoctri3110/onGKCloudConfig
          default-label: main
        bootstrap: false